### ISSUE TITLE
dependencies: gulp-minify-css deprecation

### ISSUE THREAD

**Issue by scniro** [dsebastien/modernWebDevBuild#104]
[gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) has been in deprecated in favor of [gulp-clean-css](https://github.com/scniro/gulp-clean-css). Please open an [issue](https://github.com/scniro/gulp-clean-css/issues) with the new repository if you do upgrade and experience any unexpected behavior. I look forward to maintaining this package moving forward.

**Comment by dsebastien** [comment]
Good to know, thanks @scniro. I'll try it out
