### ISSUE TITLE
npmjs.com usage info

### ISSUE THREAD

**Issue by jbeckton** [dsebastien/modernWebDevBuild#112]
Update your usage info to include the installation of JSPM. For those of us that have never used it cannot run your app created by the generator.

 npm install jspm -g

npm install jspm --save-dev

jspm init

**Comment by dsebastien** [comment]
Hey there
You don't necessarily need to install jspm globally. On the contrary I'm more against the idea. I usually run jspm from node_modules.

You can do so by adding a script like the following in your package.json:

```
"jspm": "jspm install"
```

With that, you can run ```npm run jspm``` and have jspm dependencies installed.
Take a look at the "setup" script over there: https://github.com/dsebastien/modernWebDevGenerator/blob/master/app/templates/projectTemplates/package.json

Don't hesitate to submit a PR for the docs though :)
