### ISSUE TITLE
out of the box fail

### ISSUE THREAD

**Issue by jbeckton** [dsebastien/modernWebDevBuild#113]
followed your instructions, discovered some missing steps but still does not work.

![screen shot 2016-03-11 at 9 03 31 pm](https://cloud.githubusercontent.com/assets/2669585/13720706/cf15561a-e7cc-11e5-981a-4350cf3a2c98.png)

**Comment by dsebastien** [comment]
I should probably ditch the readme docs, I've had trouble maintaining it up to date. If you want a working starting point then you're better off generating a project using the generator: https://www.npmjs.com/package/generator-modern-web-dev
