### ISSUE TITLE
npm run-script build doesn't produce a "dist" directory

### ISSUE THREAD

**Issue by eboto** [dsebastien/modernWebDevBuild#114]
The default `npm run-script build` is specified as `npm run-script compile && npm run-script test`. Unfortunately, `npm run-script test` depends upon `prepare-unit-test` which depends upon `clean`!

So the build first creates the `dist` directory with `npm run-script compile`, then _deletes_ it with `npm run-script test`.

We should probably reverse those two yeah?

**Comment by dsebastien** [comment]
I missed this one, sorry to reply so late. Indeed there's something wrong here, but with the project generator. I'll follow this up here: https://github.com/dsebastien/modernWebDevGenerator/issues/99
