### ISSUE TITLE
Watcher task crashes

### ISSUE THREAD

**Issue by bautistaaa** [dsebastien/modernWebDevBuild#130]
I searched the issues and didn't see this and it could possibly be an issue on my end.
When I pull the latest version it looks like in gulp/utils.js line 51 my code says 
`    if (exitOnError) {
        process.exit(1);
    } else {
        undefined.emit("end");
    }`

so it clearly fails in the else. however in your repo i see you changed it to this.emit.
I'm assuming that would show up in the package im getting as well?

**Comment by dsebastien** [comment]
Weird that you get undefined there :o
Indeed it should be this so that it just keeps the watcher alive...

**Comment by dsebastien** [comment]
I took that code from there: http://blog.ibangspacebar.com/handling-errors-with-gulp-watch-and-gulp-plumber/

One possibility is that the project's build breaks that code and I didn't notice

**Comment by dsebastien** [comment]
The issue might be cause by the arrow function...

**Comment by bautistaaa** [comment]
if you install your package are you getting the same thing? I was feeling like it was just me since no one else has complained about it :(

**Comment by gilbertlucas46** [comment]
I'm also seeing that error

**Comment by dsebastien** [comment]
I'm pretty sure it's caused by the arrow function, it can't work like this

**Comment by dsebastien** [comment]
I published 0.5.4, which should fix this: https://github.com/dsebastien/modernWebDevBuild/releases/tag/0.5.4

**Comment by gilbertlucas46** [comment]
nice! thanks!

**Comment by gilbertlucas46** [comment]
theres no instruction for upgrade

**Comment by dsebastien** [comment]
Just bump the dependency to 0.5.4, that should be enough I think: https://github.com/dsebastien/modernWebDevBuild/blob/master/UPGRADE.MD
