### ISSUE TITLE
Please explain how to add twitter bootstrap.js to project

### ISSUE THREAD

**Issue by gilbertlucas46** [dsebastien/modernWebDevBuild#131]
this part didn't work

import bootstrap's stylesheet(s) in vendor.scss (under styles)
you should find it somewhere under jspm_packages
see how i do the import there: https://github.com/dsebastien/midnightLightV2/blob/master/app/styles/vendor.scss
import bootstrap
you could do this in core/boot.ts for example (i.e., even before angular is loaded): https://github.com/dsebastien/midnightLightV2/blob/master/app/core/boot.ts
it could be as simple as import * from "bootstrap"; (didn't test)

![image](https://cloud.githubusercontent.com/assets/5719346/15919851/c9eccea4-2e47-11e6-99f5-addfac99d240.png)

![image](https://cloud.githubusercontent.com/assets/5719346/15922545/cf43e564-2e5a-11e6-9908-c1e6e88b8970.png)

![image](https://cloud.githubusercontent.com/assets/5719346/15923550/6cb3d1f6-2e60-11e6-83b6-a672212e8720.png)

**Comment by gilbertlucas46** [comment]
ok i got it to work

**Comment by dsebastien** [comment]
closing as it's now a different issue
