### ISSUE TITLE
Grabbing ts files from a different directory

### ISSUE THREAD

**Issue by bautistaaa** [dsebastien/modernWebDevBuild#162]
Hey there,

I started a new project basically just copy and pasting my previous package,json. Npm install everything starts up fine but for some reason when it is compiling it is somehow grabbing files from my other project and place in my temp folder and my app folder.(ie: components in my current project is empty, build and it is populated with ts files from a completely different directory) any ideas? Everything is out of the box at the moment.

Thanks!

**Comment by dsebastien** [comment]
Hello.

That is really really weird ^^.

**Comment by bautistaaa** [comment]
is there a file in particular that would possibly give it the wrong root path? this is craziness

**Comment by bautistaaa** [comment]
nm i think its a windows thing not deleting files properly when i copy and pasted the directory over

**Comment by dsebastien** [comment]
heh okay :)

**Comment by dsebastien** [comment]
FYI I don't really maintain this much anymore. I really think Webpack is the way to go for now
