### ISSUE TITLE
Wrong description comment in boot.ts

### ISSUE THREAD

**Issue by JanOschii** [dsebastien/modernWebDevBuild#85]
code/boot.ts
```
 provide(LocationStrategy, { useClass: PathLocationStrategy }) // enables the following: /#/<component_name> rather than /<component_name>
```
As far as I understand this. The default LocationStrategy is PathLocationStrategy and use  / rather than /#/

[PathLocationStrategy](https://angular.io/docs/ts/latest/api/router/PathLocationStrategy-class.html)
[HashLocationStrategy](https://angular.io/docs/ts/latest/api/router/HashLocationStrategy-class.html)

**Comment by dsebastien** [comment]
Indeed, that's a leftover from an older version where I specified the HashLocationStrategy.

At some point I added CORS support and an example htaccess file for URL rewriting and I didn't need the HashLocationStrategy anymore.

Note that the Angular team recommends using PathLocationStrategy, and for good reason, thus unless you can't configure URL rewriting on your server, you should be using that strategy.

Nice URLs are good for health .. or so I've heard :)

I'll fix this in the generator through there: https://github.com/dsebastien/modernWebDevGenerator/issues/62
