### ISSUE TITLE
Add Express server for fullstack app?

### ISSUE THREAD

**Issue by prelator** [dsebastien/modernWebDevBuild#90]
The Gulp server in the build system will not work for using this as a full-stack node app. I need to be able to integrate with with an Express server in order to add a RESTful API. Can I just add an Express server that serves the dist folder statically?

**Comment by dsebastien** [comment]
The goal with the dist contents generated by "npm run build" is to have a production version that you can just serve as is (e.g., using http-server, nginx or whatever else you like).
