### ISSUE TITLE
Please explain how to add twitter bootstrap.js to project.

### ISSUE THREAD

**Issue by pilot911** [dsebastien/modernWebDevBuild#97]
First - thanks for one of the best project for angular2! 

And please - add some lines to manual how to add twitter bootstrap.js to config and install. Thanks!

**Comment by dsebastien** [comment]
Hey there,

Well basically you should:
* use jspm to install boostrap (e.g., jspm install bootstrap)
* import bootstrap's stylesheet(s) in vendor.scss (under styles)
  * you should find it somewhere under jspm_packages
  * see how i do the import there: https://github.com/dsebastien/midnightLightV2/blob/master/app/styles/vendor.scss
* import bootstrap
  * you could do this in core/boot.ts for example (i.e., even before angular is loaded): https://github.com/dsebastien/midnightLightV2/blob/master/app/core/boot.ts
    * it could be as simple as `import * from "bootstrap";` (didn't test)

If you succeed then don't hesitate to send a PR with docs as that could be useful for others.
Maybe we could create a wiki to host that kind of information

**Comment by pilot911** [comment]
Thank you. Will try and report.

**Comment by JanOschii** [comment]
+1 For a Wiki.
Am 19.02.2016 14:27 schrieb "pilot911" <notifications@github.com>:

**Comment by dsebastien** [comment]
There it is: https://github.com/dsebastien/modernWebDevBuild/wiki :)

**Comment by dsebastien** [comment]
Don't hesitate to add this to the wiki!

**Comment by gilbertlucas46** [comment]
bash: jspm: command not found
![image](https://cloud.githubusercontent.com/assets/5719346/15919193/74eac92a-2e41-11e6-8156-5c36edb5a51f.png)

**Comment by dsebastien** [comment]
@gilbertlucas46 `npm install -g jspm`

**Comment by gilbertlucas46** [comment]
right!  thanks

**Comment by gilbertlucas46** [comment]
this part didn't work

import bootstrap
you could do this in core/boot.ts for example (i.e., even before angular is loaded): https://github.com/dsebastien/midnightLightV2/blob/master/app/core/boot.ts
it could be as simple as import * from "bootstrap"; (didn't test)
